#!/bin/sh
i3lock -n \
  --color=1a0a2e \
  --clock \
  --indicator \
  --time-str="%H:%M" \
  --date-str="%A, %d de %B de %Y" \
  --time-color=e8d5ffff \
  --date-color=b39ddbff \
  --inside-color=1a0a2eaa \
  --ring-color=7c3aedff \
  --ringver-color=9575cdff \
  --ringwrong-color=cc0066ff \
  --insidever-color=1a0a2eaa \
  --insidewrong-color=2d0a50aa \
  --keyhl-color=e8d5ffff \
  --bshl-color=cc0066ff \
  --separator-color=00000000 \
  --line-color=00000000 \
  --verif-color=e8d5ffff \
  --wrong-color=cc0066ff &
sleep 1 && xset dpms force off &
wait
